services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        networks:
            - app_network
        depends_on:
            - db
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=testDB
            - DB_USERNAME=user
            - DB_PASSWORD=password

    db:
        image: postgres:14.5
        environment:
            POSTGRES_DB: testDB
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    db_data:
